### PR TITLE
Reconnect on connection close

### PR DESCRIPTION
**Pull request by Sadovnikov94**
Start trying to connect every 10 seconds, if auto reconnect do not help

### CODE REVIEW

**Comment by Sadovnikov94** [comment]
Not well formed decision

**Comment by carlosCharz** [comment]
I was analyzing the solution. What happened?

Best regards,

*Carlos Becerra Rodriguez*
*MSc. Software & Systems - **Universidad Politécnica de Madrid*
*Software Engineer - **Pontificia Universidad Católica del Perú*

**Comment by Sadovnikov94** [comment]
Connection has not auto reconnect by ReconnectionManager
ReconnectionManager tried to open connection just once after fail
Changing reconnection policy will fixed this issue

**Comment by carlosCharz** [comment]
Cool man.

Best regards,

*Carlos Becerra Rodriguez*
*MSc. Software & Systems - **Universidad Politécnica de Madrid*
*Software Engineer - **Pontificia Universidad Católica del Perú*

**Pull request closed without merging**
